name: Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  tests-misc:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-feathersui ${{ github.workspace }}
      - name: Run Neko Tests
        working-directory: test
        run: |
          haxelib run openfl test neko
      - name: Run HTML5 Tests
        working-directory: test
        run: |
          npm ci
          npx playwright install
          npx playwright install-deps
          haxelib run openfl build html5 -Dplaywright
          node playwright-runner.js
  tests-hashlink:
    strategy:
      matrix:
        haxe-version: [4.0.5, 4.1.5, 4.2.5, 4.3.4]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cedx/setup-hashlink@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-feathersui ${{ github.workspace }}
      - name: Run HashLink Tests
        working-directory: test
        run: |
          haxelib run openfl test hl
  tests-air:
    strategy:
      matrix:
        haxe-version: [4.3.4]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joshtynjala/setup-adobe-air-action@v2
        with:
          air-version: "33.1"
          accept-license: true
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe-version }}
      - name: Set up Haxelib dependencies
        run: |
          haxelib install utest --quiet
          haxelib install hxcpp --quiet
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install feathersui --quiet
          haxelib git bindable https://github.com/mxhx-dev/bindable.git --quiet
          haxelib git mxhx-component https://github.com/mxhx-dev/mxhx-component.git --quiet
          haxelib git mxhx-runtime-component https://github.com/mxhx-dev/mxhx-runtime-component.git --quiet
          haxelib dev mxhx-feathersui ${{ github.workspace }}
          haxelib run lime config AIR_SDK ${{ env.AIR_HOME }}
      - name: Run AIR Tests
        working-directory: test
        run: |
          haxelib run openfl test air
